# Generated by Django 4.1.2 on 2022-10-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
